### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by Emirismail** [ooza/AcTiV-annotation-tool#1]
Could you provide us with some more details on the requirements of the tool:

- Specifications of the videos to annotate
- Do we need to load a pre-model?
- If it is possible, could you, please, illustrate the workflow of your tool?

Thank you.

**Comment by ooza** [comment]
Hi
- It's a desktop application implemented in Java to annotate video clips of Arabic news but you can use it, more specifically the detection part, to annotate any other language.
- The tool isn't based on any ML module so you do not need to load a pre-model . All the required packages are in the lib folder. 
- More information are available [here](https://icosys.ch/wp-content/uploads/pdfs/oussama2018arabictext.pdf) page 50
